### ISSUE TITLE
your time estimated at weekend is unusable

### ISSUE THREAD

**Issue by vickiegpt** [LyricZhao/THU-Bell#1]
before the nextIndex is --, if do not satisfy the stmt `currentTime >= times[times.count - 1] || nextWeekDay > 5 { // or nextWeekDay > 5`  which is on weekend. the nextIndex remains undefined(nil) if started at weekend. suggest redefine nextIndex in the else stmt.
```
//        if currentTime >= times[times.count - 1] || nextWeekDay > 5 { // or nextWeekDay > 5
            nextIndex = times.count
//        } else {
//            for (index, time) in times.enumerated() {
//                if currentTime >= time {
//                    nextIndex = index + 1
//                } else {
//                    break
//                }
//            }
//        }
```

**Comment by LyricZhao** [comment]
Thanks for your comment. I'll fix it later.
