### ISSUE TITLE
macOS 10.14 support?

### ISSUE THREAD

**Issue by SunnyHZB** [LyricZhao/THU-Bell#4]
Hi! I was wondering if it is possible to add support for 10.14 version of macOS, because now it requires 10.15 or later to run. (I, and maybe some other people as well, don't want to upgrade to 10.15 because it has stopped supporting 32-bit applications...)
If it's too much trouble then just forget it. Just asking.
Thanks!

**Comment by LyricZhao** [comment]
Thanks for your comments. I'll fix it later.

**Comment by LyricZhao** [comment]
I've already added the support. Please check whether it works. Thanks for your comments.
Download Link: https://github.com/LyricZhao/THU-Bell/releases
